--- @meta

LibChatMessage = {}
LibFBCommon = {}
LibGroupBroadcast = {}
LibInfiniteArchive = {}
LibSavedVars = {}

ACHIEVEMENTS_MANAGER = {}
BOSS_BAR = {}
CENTER_SCREEN_ANNOUNCE = {}
COMPASS = {}
ENDLESS_DUNGEON_MANAGER = {}
SHARED_INVENTORY = {}

ACTION_RESULT_DIED = 2260
ACTION_RESULT_DIED_XP = 2262
ARCHIVEHELPER_WEREWOLF_BEHEMOTH = 0
ENDLESS_DUNGEON_BUFF_TYPE_VERSE = 1
ENDLESS_DUNGEON_BUFF_TYPE_VISION = 2
ENDLESS_DUNGEON_GROUP_TYPE_SOLO = 0
HOTBAR_CATEGORY_PRIMARY = 0
HOTBAR_CATEGORY_TEMPORARY = 9
LIBINFINITEARCHIVE_AUDITOR_NAME = 0
LIBINFINITEARCHIVE_TOMESHELL = 0
MAP_PIN_TYPE_QUEST_INTERACT = 8
MAX_PET_UNIT_TAGS = 7
SKILL_TYPE_AVA = 6
SKILL_TYPE_CLASS = 1
SKILL_TYPE_GUILD = 5
SKILL_TYPE_WORLD = 4

ZO_ACHIEVEMENTS_COMPLETION_STATUS = {
    COMPLETE = 1
}

--- @alias EndlessDungeonGroupType integer
